import Head from 'next/head'
import styles from '../styles/Home.module.css'
import BlogCard from '../components/BlogCard';

import { GraphQLClient, gql } from 'graphql-request'

const graphcms = new GraphQLClient('https://api-eu-central-1.hygraph.com/v2/cl7yl6zkp3men01ul9sci804k/master');

const QUERY = gql`
 {
    posts {
      id,
      title,
      datePublished,
      slug,
      content {
        html
      }
    author {
      name,
      avatar {
        url
      }
    }
    coverPhoto {
      url
    }
  }
}
`

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
  }
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            datePublished={post.datePublished}
            slug={post.slug}
            key={post.id}
          />)
        )}
      </main>
    </div>
  )
}
